language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
os:
  - linux
before_install:
  - pip install git+https://github.com/pepkit/ubiquerg.git@dev
install:
  - pip install .
  - pip install -r requirements/requirements-dev.txt
  - pip install -r requirements/requirements-test.txt
script: pytest tests --cov=yacman
branches:
  only:
    - dev
    - master
