name: Test locking parallel

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  locking_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
        proc: [10, 100]
        wait: [10, 40]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Install dev dependencies
      run: if [ -f requirements/requirements-dev.txt ]; then pip install -r requirements/requirements-dev.txt; fi

    - name: Install yacman
      run: python -m pip install .

    - name: Run locking tests (processes=${{ matrix.proc }}, max wait time=${{ matrix.wait }})
      run: |
        cd locking_tests
        ./run_locking_tests.sh ${{ matrix.proc }} ${{ matrix.wait }}
